language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-18
    - ANDROID_ABI=armeabi-v7a

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.0
  - android-25
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

before_install:
 - chmod +x gradlew

licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew build
