language: android
dist: precise

jdk:
  - oraclejdk8

sudo:
  required

env:
  matrix:
    - ANDROID_TARGET=android-24 ANDROID_ABI=armeabi-v7a
    #- ANDROID_TARGET=android-24 ANDROID_ABI=x86
  global:
    # wait up to 10 minutes for adb to connect to emulator
    - ADB_INSTALL_TIMEOUT=20

android:
    components:
        - tools
        - build-tools-25.0.0
        - android-24
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository

    licenses:
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
    bundler: true
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - node_modules
        - $HOME/ve
        #- $HOME/docker

before_install:
  - sudo mkdir $ANDROID_HOME/licenses
  - sudo touch "$ANDROID_HOME/licenses/android-sdk-license"
  - sudo bash -c 'sudo echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" >> "$ANDROID_HOME/licenses/android-sdk-license"'

before_script:
  - chmod +x gradlew
  - sudo chmod u+x createPassfile
  - sudo ./createPassfile -pwd $KEYSTORE_PASS;

script:
    - if [ $TRAVIS_BRANCH == "release_candidate" ]; then ./gradlew assembleStagingRelease crashlyticsUploadDistributionStagingRelease; else ./gradlew assembleStagingRelease; fi